server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/v1/orders/**
            - Method=GET,POST,PUT,PATCH,DELETE
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Request-header, jatin

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
            - Method=GET,POST,PUT,PATCH,DELETE
          filters:
            - name: InventoryLoggingFilter
            - name: Authentication
              args:
                isEnabled: false
            - name: Authorization
              args:
                roles: ADMIN,USER

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: a-string-secret-at-least-256-bits-long
