deploy:
  env: default
server:
  port: 8081

  servlet:
    context-path: /inventory

spring:
  #  data base config :
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


  #  hibernate & jpa
  jpa:
    hibernate:
      ddl-auto: update

    defer-datasource-initialization: true

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: NEVER

management:
  endpoints:
    web:
      exposure:
        include: *
